const htmlEventNames = [
	"onabort",
	"onanimationend",
	"onanimationiteration",
	"onanimationstart",
	"onblur",
	"oncanplay",
	"oncanplaythrough",
	"onchange",
	"onclick",
	"oncopy",
	"oncut",
	"ondblclick",
	"ondrag",
	"ondragend",
	"ondragenter",
	"ondragleave",
	"ondragover",
	"ondragstart",
	"ondrop",
	"ondurationchange",
	"onended",
	"onerror",
	"onfocus",
	"oninput",
	"oninvalid",
	"onkeydown",
	"onkeypress",
	"onkeyup",
	"onload",
	"onloadeddata",
	"onloadedmetadata",
	"onloadstart",
	"onmousedown",
	"onmouseenter",
	"onmouseleave",
	"onmousemove",
	"onmouseover",
	"onmouseup",
	"onpaste",
	"onpause",
	"onplay",
	"onplaying",
	"onprogress",
	"onratechange",
	"onscroll",
	"onseeked",
	"onseeking",
	"onselect",
	"onstalled",
	"onsubmit",
	"onsuspend",
	"ontimeupdate",
	"ontoggle",
	"ontouchcancel",
	"ontouchend",
	"ontouchmove",
	"ontouchstart",
	"ontransitionend",
	"onvolumechange",
	"onwaiting",
	"onwheel",
] as const;

export type HTMLEventName = typeof htmlEventNames[number];

export function isEventName(name: string): name is HTMLEventName {
	// @ts-expect-error
	if (htmlEventNames.indexOf(name) !== -1) {
		return true;
	}
	return false;
}
